#!/usr/bin/env python3
"""Rewrite the hamburger panel in every page from data/nav-partial.html.

SOURCE OF TRUTH IS data/nav-partial.html. There are deliberately no link
labels, hrefs, or section names anywhere in this file -- if you are here to
rename a menu item, you are in the wrong file. Edit the partial and re-run.

    python3 generate_nav.py --check    # report drift, write nothing
    python3 generate_nav.py            # rewrite panels in place

The partial uses {{BASE}} in front of every site-relative href/src. This
script substitutes the correct number of ../ hops per page. External links
carry no token and pass through untouched.
"""
import re
import sys
from pathlib import Path

PARTIAL = "data/nav-partial.html"
START = "<!-- NAV:START - generated by generate_nav.py from data/nav-partial.html. Do not edit by hand. -->"
END = "<!-- NAV:END -->"

SKIP_DIRS = {".git", "assets", "csv", "node_modules"}
# The partial IS a panel, so it matches every heuristic here. Excluding it
# explicitly stops the tooling from processing its own source of truth.
SKIP_FILES = {"data/nav-partial.html"}

# Templates live at one path but their OUTPUT is written somewhere else, so the
# ../ depth cannot be inferred from where the template sits on disk. These are
# output locations, not link names.
DEPTH_OVERRIDES = {
    "data/collection-template.html": 1,  # rendered into collections/
    "data/guide-template.html": 2,       # rendered into data/guides/
    "data/article-template.html": 1,     # rendered into articles/
}

# Templates must never get a 'current' highlight -- they are not a page.
NO_CURRENT = set(DEPTH_OVERRIDES)


def depth_for(rel):
    key = rel.as_posix()
    if key in DEPTH_OVERRIDES:
        return DEPTH_OVERRIDES[key]
    return len(rel.parts) - 1


def render(partial, depth, self_href):
    """Substitute {{BASE}} and mark the link pointing at this page as current."""
    base = "../" * depth
    out = partial.replace("{{BASE}}", base)

    if self_href is None:
        return out

    target = base + self_href

    def mark(m):
        if m.group("href") != target:
            return m.group(0)
        cls = m.group("cls")
        if cls is None:
            return f'<a href="{m.group("href")}" class="current"{m.group("rest")}>'
        if "current" in cls.split():
            return m.group(0)
        # Existing convention across the site puts 'current' first.
        return f'<a href="{m.group("href")}" class="current {cls}"{m.group("rest")}>'

    return re.sub(
        r'<a href="(?P<href>[^"]+)"(?:\s+class="(?P<cls>[^"]*)")?(?P<rest>[^>]*)>',
        mark,
        out,
    )


def main():
    check = "--check" in sys.argv
    root = Path(__file__).resolve().parent

    partial_path = root / PARTIAL
    if not partial_path.exists():
        print(f"missing {PARTIAL}", file=sys.stderr)
        return 1
    partial = partial_path.read_text(encoding="utf-8").strip()

    if "{{BASE}}" not in partial:
        print(f"{PARTIAL} contains no {{{{BASE}}}} tokens -- refusing to run", file=sys.stderr)
        return 1

    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)

    written = unchanged = 0
    drifted = []
    missing_markers = []

    for path in sorted(root.rglob("*.html")):
        rel = path.relative_to(root)
        if SKIP_DIRS & set(rel.parts) or rel.as_posix() in SKIP_FILES:
            continue

        html = path.read_text(encoding="utf-8")
        if START not in html:
            if '<div class="hamburger-panel"' in html:
                missing_markers.append(rel.as_posix())
            continue

        if len(pattern.findall(html)) != 1:
            print(f"  ERROR {rel}: expected exactly 1 marker block", file=sys.stderr)
            continue

        key = rel.as_posix()
        self_href = None if key in NO_CURRENT else key.split("/")[-1] if len(rel.parts) == 1 else key
        block = START + "\n" + render(partial, depth_for(rel), self_href) + "\n" + END
        new = pattern.sub(lambda _: block, html, count=1)

        if new == html:
            unchanged += 1
            continue

        drifted.append(rel.as_posix())
        if not check:
            # Write immediately per file rather than batching, so a later
            # failure cannot discard edits that already succeeded.
            path.write_text(new, encoding="utf-8")
            written += 1

    verb = "would update" if check else "updated"
    print(f"{verb:>14}: {len(drifted) if check else written}")
    print(f"{'already current':>14}: {unchanged}")
    for d in drifted[:20]:
        print("   ~ " + d)
    if len(drifted) > 20:
        print(f"   ... and {len(drifted) - 20} more")

    if missing_markers:
        print(f"\n{len(missing_markers)} file(s) have a panel but no markers -- run insert_nav_markers.py:")
        for m in missing_markers[:10]:
            print("  " + m)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
