#!/usr/bin/env python3
"""One-time: wrap each page's existing hamburger panel in NAV markers.

Run this ONCE. After it, generate_nav.py owns everything between the markers
and this script is dead weight -- it refuses to touch a file that already has
markers, so re-running it is a no-op rather than a corruption.

It does NOT rewrite nav content. It only inserts two comment lines. Content
drift gets fixed on the first generate_nav.py run, so the two steps stay
independently reviewable in git.

    python3 insert_nav_markers.py --check    # report only, write nothing
    python3 insert_nav_markers.py            # insert markers
"""
import re
import sys
from pathlib import Path

START = "<!-- NAV:START - generated by generate_nav.py from data/nav-partial.html. Do not edit by hand. -->"
END = "<!-- NAV:END -->"

SKIP_DIRS = {".git", "assets", "csv", "node_modules"}
# The partial IS a panel, so it matches every heuristic here. Excluding it
# explicitly stops the tooling from processing its own source of truth.
SKIP_FILES = {"data/nav-partial.html"}
PANEL_OPEN = '<div class="hamburger-panel"'


def find_panel(html):
    """Return (start, end) of the panel by matching <div> nesting, not regex.

    A non-greedy regex stops at the first </div>, which lands mid-panel. This
    walks the tag stream instead, so nested sections are handled correctly.
    """
    start = html.find(PANEL_OPEN)
    if start < 0:
        return None
    depth = 0
    for m in re.finditer(r"<div\b|</div>", html[start:]):
        if m.group(0) == "</div>":
            depth -= 1
            if depth == 0:
                return start, start + m.end()
        else:
            depth += 1
    return None


def iter_html(root):
    for p in sorted(root.rglob("*.html")):
        rel = p.relative_to(root)
        if SKIP_DIRS & set(rel.parts) or rel.as_posix() in SKIP_FILES:
            continue
        yield p


def main():
    check = "--check" in sys.argv
    root = Path(__file__).resolve().parent

    changed = skipped = already = no_panel = 0
    failures = []

    for path in iter_html(root):
        html = path.read_text(encoding="utf-8")

        if START in html:
            already += 1
            continue

        span = find_panel(html)
        if span is None:
            no_panel += 1
            continue

        a, b = span
        panel = html[a:b]

        # Assert on what we are about to wrap, so a malformed match can never
        # be silently written out. Half-removed constructs only fail at runtime.
        if html.count(PANEL_OPEN) != 1:
            failures.append(f"{path}: expected 1 panel, found {html.count(PANEL_OPEN)}")
            continue
        if not panel.rstrip().endswith("</div>"):
            failures.append(f"{path}: panel match does not end in </div>")
            continue
        if "hamburger-section" not in panel:
            failures.append(f"{path}: panel match contains no hamburger-section")
            continue
        if END in html:
            failures.append(f"{path}: END marker present without START")
            continue

        new = html[:a] + START + "\n" + panel + "\n" + END + html[b:]

        # The only permitted delta is the two marker lines.
        if new.replace(START + "\n", "", 1).replace("\n" + END, "", 1) != html:
            failures.append(f"{path}: insertion changed more than the markers")
            continue

        if check:
            skipped += 1
        else:
            path.write_text(new, encoding="utf-8")
            changed += 1

    print(f"{'would wrap' if check else 'wrapped':>12}: {skipped if check else changed}")
    print(f"{'already':>12}: {already}")
    print(f"{'no panel':>12}: {no_panel}")
    if failures:
        print(f"\n{len(failures)} FAILURE(S) -- these files were left untouched:")
        for f in failures:
            print("  " + f)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
